name: Mirror to Gitea
on:
  workflow_call:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Push to Gitea
        run: |
          git remote add gitea https://oauth2:${{ secrets.GITEA_TOKEN }}@git.almaroo.work/almaroo/${{ github.event.repository.name }}.git
          git push gitea --tags HEAD:master
